
#sdk: "/Library/Ruby/Gems/1.8/gems/rhodes-3.2.0.beta.5"
sdkversion: 3.2.0
name: SHIFT
version: 1.0
vendor: rhomobile
build: debug
bbver: 4.6
wmsdk: Windows Mobile 6 Professional SDK (ARMV4I)
applog: rholog.txt
iphone:
  configuration: Release
  sdk: iphoneos5.0
  provisionprofile: 1800DDB1-580D-4CAC-BB93-DDF40D57CBF2
  codesignidentity: iPhone Developer
  entitlements: 
  BundleIdentifier: com.rhomobile.SHIFT
  BundleURLScheme: SHIFT
wp:
  productid: 3cc0f680-db49-012e-1015-388d1200f926
symbian:
  uid: 3786915627
android:
  version: 2.1
  emulator: test2.2
extensions:
  - json
  - barcode
capabilities:
  - camera
